name: "Carrion Language Build & Release"

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to access branch history
          persist-credentials: true  # Required for subsequent pushes

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Extract version from tag
        id: version_info
        run: |
          RAW_VERSION="${GITHUB_REF##*/}"    # e.g. "v1.0.0"
          VERSION="${RAW_VERSION#v}"        # e.g. "1.0.0"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update README version
        run: |
          # Update version in README
          sed -i "s/{{VERSION}}/$VERSION/g" docs/README.md
          
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Commit changes
          git add docs/README.md
          git commit -m "📚 Update README to version $VERSION"
          
          # Push to main branch
          git push origin HEAD:main

      - name: Build Artifacts
        run: |
          make build-source
          make build-linux
          make build-windows

      - name: Docker login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Docker build and push
        run: |
          make build USER_NAME=$DOCKER_USERNAME VERSION=${{ env.VERSION }}
          make push USER_NAME=$DOCKER_USERNAME VERSION=${{ env.VERSION }}

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Carrion Release ${{ env.VERSION }}"
          files: |
            carrion-src.tar.gz
            carrion_linux_amd64.tar.gz
            carrion_windows_amd64.zip
